registry:
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  volumes:
    - ./data:/data
registry-ui:
  image: konradkleine/docker-registry-frontend:v2
  ports:
    - 8887:80
  environment:
    ENV_DOCKER_REGISTRY_HOST: 192.168.1.8
    ENV_DOCKER_REGISTRY_PORT: 5000