apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: localmovies-keycloak
  name: localmovies-keycloak
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/localmovies-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localmovies-keycloak
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: localmovies-keycloak
    spec:
      containers:
      - image: 192.168.1.8:5000/keycloak
        imagePullPolicy: Always
        name: localmovies-keycloak
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsConfig:
        nameservers:
         - 8.8.8.8
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}

