# helm upgrade --install -n artifactory artifactory jfrog/artifactory-oss --values artifactory/values.yml
# Gateway API: kubectl apply -f artifactory/httproute.yml -f artifactory/backend-policy.yml -f artifactory/client-policy.yml

artifactory:
  observability:
    enabled: false
  postgresql:
    enabled: false
  artifactory:
    persistence:
      existingClaim: artifactory-artifactory-2

  nginx:
    enabled: false

  ingress:
    enabled: false
