apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-output
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.capacity.output }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.capacity.data }}