# helm upgrade --install -n monitoring kube-prometheus-stack prometheus-community/kube-prometheus-stack --values prometheus/values.yml
# Gateway API: kubectl apply -f prometheus/grafana-httproute.yml

grafana:
  assertNoLeakedSecrets: false
  grafana.ini:
    users:
      viewers_can_edit: false
    auth:
      disable_login_form: false
      disable_signout_menu: false
    auth.anonymous:
      enabled: true
      org_role: Viewer
    database:
      type: postgres
      host: postgres-rw.postgres-18:5432
      name: grafana
      user: grafana
      password: pw123
  ingress:
    enabled: false
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    retention: 60d
    additionalScrapeConfigs:
    - job_name: 'localmovies'
      scheme: http
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['localmovies.localmovies:8080']
    - job_name: 'postgres'
      scheme: http
      metrics_path: '/metrics'
      static_configs:
        - targets: ['postgresql-metrics.postgres:9187']
    - job_name: 'nextcloud'
      scheme: http
      metrics_path: '/metrics'
      scrape_timeout: 30s
      static_configs:
        - targets: ['nextcloud-metrics.nextcloud:9205']
alertmanager:
  alertmanagerSpec:
    alertmanagerConfigNamespaceSelector: {}
    alertmanagerConfigSelector: {}