grafana:
  persistence:
    enabled: true
  grafana.ini:
    users:
      viewers_can_edit: false
    auth:
      disable_login_form: false
      disable_signout_menu: false
    auth.anonymous:
      enabled: true
      org_role: Viewer
  ingress:
      enabled: true
      hosts:
      - grafana.nathanrahm.com
      path: /
      annotations:
          certmanager.k8s.io/cluster-issuer: letsencrypt-prod
          ingress.kubernetes.io/ssl-redirect: "true"
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
          nginx.ingress.kubernetes.io/enable-modsecurity: "true"
          nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
          nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
      tls:
        - hosts:
            - grafana.nathanrahm.com
          secretName: grafana-ingress-tls
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'localmovies'
      scheme: http
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['localmovies.localmovies:8080']