# helm upgrade --install -n sonarqube sonarqube sonarqube/sonarqube --values sonarqube/values.yml
# Gateway API: Create httproute.yml if deploying (not currently deployed)

ingress:
  enabled: false

persistence:
  enabled: true

jdbcOverwrite:
  # If enable the JDBC Overwrite, make sure to set `postgresql.enabled=false`
  enable: true
  enabled: true
  # The JDBC url of the external DB
  jdbcUrl: "jdbc:postgresql://postgres-rw.postgres-18.svc.cluster.local:5432/sonarqube?socketTimeout=1500"
  # The DB user that should be used for the JDBC connection
  jdbcUsername: "sonarqube"
  # Use this if you don't mind the DB password getting stored in plain text within the values file
  jdbcPassword: "pw123"

postgresql:
  enabled: false
