# helm upgrade --install -n sonarqube sonarqube sonarqube/sonarqube --values sonarqube/values.yml

ingress:
  enabled: true
  hosts:
    - name: sonarqube.nathanrahm.com
  annotations:
    kubernetes.io/tls-acme: 'true'
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
#    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
#    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"

persistence:
  enabled: true

jdbcOverwrite:
  # If enable the JDBC Overwrite, make sure to set `postgresql.enabled=false`
  enable: true
  enabled: true
  # The JDBC url of the external DB
  jdbcUrl: "jdbc:postgresql://postgresql.postgres.svc.cluster.local:5432/sonarqube?socketTimeout=1500"
  # The DB user that should be used for the JDBC connection
  jdbcUsername: "sonarqube"
  # Use this if you don't mind the DB password getting stored in plain text within the values file
  jdbcPassword: "pw123"

postgresql:
  enabled: false
