# helm install -n stable-diffusion oauth2-proxy ./oauth2-proxy --values oauth2-proxy/values.yaml --values oauth2-proxy/values-sd.yaml

ingress:
  hostname: sd.nathanrahm.com
  tlsSecretName: stable-diffusion-tls

cookieSecret: <cookie-secret>

keycloak:
  realm: NathanRahm
  clientId: ollama
  clientSecret: <client-secret>
  role: ollama
