# helm install -n open-webui oauth2-proxy ./oauth2-proxy --values oauth2-proxy/values.yaml --values oauth2-proxy/values-ollama.yaml

ingress:
  hostname: ollama.nathanrahm.com
  tlsSecretName: ollama-tls

cookieSecret: <cookie-secret>

keycloak:
  realm: Ollama
  clientId: ollama
  clientSecret: <client-secret>
  role: ollama
