version: '2.1'

services:
  protonmail-bridge:
    image: shenxn/protonmail-bridge
    ports:
      - "1025:25/tcp"
      - "1143:143/tcp"
    restart: unless-stopped
    volumes:
      - protonmail:/root
volumes:
  protonmail:
    name: protonmail
