# helm -n nextcloud install nextcloud nextcloud/nextcloud --values nextcloud/values.yml
# UPGRADE WARNING: Disable all health/liveness/readiness probes before upgrading or they will kill the pod mid-update.

# Backup files: aws s3 sync /srv/dev-disk-by-id-ata-Samsung_SSD_860_EVO_1TB_S4X5NE0M704625B/PersistentVolumes/nextcloud-nextcloud-nextcloud-pvc-ba0e3573-dc02-4277-9149-017290a8e0f1/ s3://rahm-nextcloud-backup/
# Backup DB: echo '<password>' | kubectl -n postgres exec -it postgresql-postgresql-0 -- pg_dump -U postgres nextcloud >> /home/nathan/Nextcloud/Developement/nextcloud-backups/nextcloud-$(date "+%Y.%m.%d-%H.%M.%S").sql

# Trigger memory index inside container: su -s /bin/bash www-data -c "./occ memories:index"

## Official nextcloud image version
## ref: https://hub.docker.com/r/library/nextcloud/tags/
##
image:
  repository: nextcloud
  tag: 31.0.2-apache
  pullPolicy: IfNotPresent

# Number of replicas to be deployed
replicaCount: 1

## Allowing use of ingress controllers
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 12G
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    # Keep this in sync with the README.md:
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;
      rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
      rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
      rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
      location = /.well-known/carddav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /.well-known/caldav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
      }
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
      }
      location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
        deny all;
      }
  tls:
    - secretName: nextcloud-tls
      hosts:
        - nextcloud.nathanrahm.com
  labels: {}
  path: /
  pathType: Prefix

nextcloud:
  host: nextcloud.nathanrahm.com
  username: nrahm
  password: <password>
  mail:
    enabled: true
    fromAddress: support
    domain: nathanrahm.com
    smtp:
      host: 10.0.0.33
      secure: STARTTLS
      port: 1025
      authtype: LOGIN
      name: <username>
      password: <password>
  defaultConfigs:
    smtp.config.php: false
  configs:
    smtp.config.php: |-
      <?php
      $CONFIG = array (
        'mail_smtpstreamoptions' =>
        array (
          'ssl' =>
          array (
            'allow_self_signed' => true,
            'verify_peer' => false,
            'verify_peer_name' => false,
          ),
        ),
      );

lifecycle:
  postStartCommand: ["/bin/bash", "-c", "apt update -y && apt install ffmpeg -y"]

externalDatabase:
  enabled: true
  type: postgresql
  host: postgresql.postgres.svc.cluster.local
  user: nextcloud
  password: pw123
  database: nextcloud
  existingSecret:
    enabled: false

persistence:
  enabled: true
  existingClaim: nextcloud-nextcloud-2
  accessMode: ReadWriteOnce
  size: 150Gi

imaginary:
  enabled: true

cronjob:
  enabled: true



##
## Disabled Stuff
##

mariadb:
  enabled: false

postgresql:
  enabled: false

redis:
  enabled: false

collabora:
  enabled: false

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
startupProbe:
  enabled: false

nginx:
  enabled: false

internalDatabase:
  enabled: false

hpa:
  enabled: false

metrics:
  enabled: false

rbac:
  enabled: false
