apiVersion: v1
kind: Service
metadata:  
  name: vault
spec:
  type: NodePort
  selector:
    app: vault
  ports:  
  - name: https
    port: 8200
    targetPort: 8200
    nodePort: 30033
    protocol: TCP
