apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: vault
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - image: vault:latest
        imagePullPolicy: Always
        name: vault
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
          - "vault"
        args:
          - "server"
          - "-config=/vault/config/config.json"
        volumeMounts:
        - name: config
          mountPath: /vault/config
          readOnly: false
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
      dnsConfig:
        nameservers:
         - 8.8.8.8
      volumes:
      - name: config
        hostPath:
          path: /mnt/data/hashicorp-vault/config
          type: Directory
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
