apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: vault
  name: vault
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vault
    spec:
      containers:
      - image: 192.168.1.8:5000/vault:latest
        imagePullPolicy: Always
        name: vault
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: config
          mountPath: /vault/config
          readOnly: true
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
      dnsConfig:
        nameservers:
         - 8.8.8.8
      volumes:
      - name: config
        hostPath:
          path: /opt/vault/config
          type: Directory
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}

