apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      serviceAccountName: oauth2-proxy
      containers:
        - args:
            - --provider=keycloak-oidc
            - --oidc-issuer-url=https://{{ .Values.keycloak.hostname }}/realms/{{ .Values.keycloak.realm }}
            - --email-domain=*
            - --skip-jwt-bearer-tokens=true
            - --client-id={{ .Values.keycloak.clientId }}
            - --client-secret={{ .Values.keycloak.clientSecret }}
            - --redirect-url=https://{{ .Values.ingress.hostname }}/oauth2/callback
            - --allowed-role={{ .Values.keycloak.role }}
            - --allowed-role="{{ .Values.keycloak.role }}:{{ .Values.keycloak.role }}"
            - --cookie-secret={{ .Values.cookieSecret }}
            - --upstream=file:///dev/null
            - --http-address=0.0.0.0:4180
          image: "{{ .Values.image.registry }}/oauth2-proxy:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          name: oauth2-proxy
