apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  type: ClusterIP
  selector:
    k8s-app: oauth2-proxy
  ports:
    - name: http
      port: 4180
