# helm install -n ingress ingress-nginx ingress-nginx/ingress-nginx --values ingress/values.yml

metrics:
  prometheusRules: true

controller:
  config:
    annotations-risk-level: Critical
    enable-modsecurity: "false"
  service:
    type: NodePort
  metrics:
    enabled: true
  podAnnotations:
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
  allowSnippetAnnotations: true