# helm install -n keycloak keycloak codecentric/keycloak --values keycloak/values.yml

ingress:
  enabled: true
  servicePort: https
  annotations:
    cert-manager.io/cluster-issuer:  letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    nginx.org/ssl-services: keycloak-http
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  rules:
    - host: 'login.nathanrahm.com'
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - login.nathanrahm.com
      secretName: keycloak-ingress-tls
postgresql:
  enabled: false

extraEnv: |
  - name: 'DB_VENDOR'
    value: 'postgres'
  - name: 'DB_ADDR'
    value: 'postgresql.postgres.svc.cluster.local'
  - name: 'DB_PORT'
    value: '5432'
  - name: 'DB_DATABASE'
    value: 'keycloak'
  - name: 'DB_USER'
    value: 'keycloak'
  - name: 'DB_PASSWORD'
    value: 'pw123'