# helm repo add codecentric https://codecentric.github.io/helm-charts
# helm install -n keycloak keycloak codecentric/keycloakx --values keycloak/values.yml

image:
  repository: quay.io/keycloak/keycloak
  tag: "25.0"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer:  letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
  rules:
    - host: 'login.nathanrahm.com'
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - login.nathanrahm.com
      secretName: keycloak-ingress-tls


http:
  relativePath: "/"

command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-port=8080"
  - "--hostname=https://login.nathanrahm.com"
dbchecker:
  enabled: true

database:
  vendor: postgres
  hostname: postgresql.postgres.svc.cluster.local
  port: 5432
  username: 'keycloak'
  password: 'pw123'
  database: keycloak

extraEnv: |
  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    value: admin
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    value: admin
  - name: KC_PROXY
    value: "passthrough"
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
