apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      hostAliases:
      - ip: 192.168.1.8
        hostnames:
        - "docker-registry"
      containers:
      - image: jenkins/jenkins:lts
        imagePullPolicy: Always
        name: jenkins
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
          readOnly: false
        - name: android-sdk
          mountPath: /etc/android-sdk
          readOnly: false
        - name: docker
          mountPath: /var/run/docker.sock
          readOnly: false
      dnsConfig:
        nameservers:
         - 8.8.8.8
      volumes:
      - name: jenkins-home
        hostPath:
          path: /mnt/data/jenkins_home
          type: Directory
      - name: android-sdk
        hostPath:
          path: /mnt/data/android_home
          type: Directory
      - name: docker
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
