# helm upgrade --install -n jenkins jenkins jenkins/jenkins --values jenkins/values.yml

controller:
  installPlugins:
    - kubernetes:4423.vb_59f230b_ce53
    - workflow-aggregator:608.v67378e9d3db_1
    - git:5.10.0
    - configuration-as-code:2053.vb_0da_47381a_25
  ingress:
      enabled: true
      hostName: jenkins.nathanrahm.com
      ingressClassName: nginx
      apiVersion: networking.k8s.io/v1
      annotations:
         cert-manager.io/cluster-issuer:  letsencrypt-prod
         ingress.kubernetes.io/ssl-redirect: "true"
         kubernetes.io/ingress.class: nginx
         kubernetes.io/tls-acme: "true"
      tls:
        - hosts:
          - jenkins.nathanrahm.com
          secretName: jenkins-tls
