{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mealie
spec:
  parentRefs:
    - name: {{ .Values.gateway.parentRef.name }}
      namespace: {{ .Values.gateway.parentRef.namespace }}
  hostnames:
    - {{ .Values.gateway.hostname }}
  rules:
    - backendRefs:
        - name: mealie
          port: {{ .Values.service.port }}
{{- end }}
