#ENC[AES256_GCM,data:CYtD0/uaDeqinSFs6ax+LfpiS/UlUZySaKYgBrmtEUBOWhSHUHVftQR8,iv:w4FX8yD2To7420w4miJwF6RqsQPLGlnQgeIeEdbE+JM=,tag:uPRIkvEajbVZdDbNRbTRBQ==,type:comment]
#ENC[AES256_GCM,data:Vr7Avo7NQe/jSkRtviSKCYf7w5uZpMIBRjzkcc+Jmu4cS8cH/EMoQmNRUZ9PWVpubPmHFexcvhoyjEJrgVa5CQ==,iv:+2U2zSFnbZOjcgcPPmlqMzNhIkL7b5kgbzo8DFjNFZA=,tag:WHTiOqvOVJ0SZRjyXiA7dw==,type:comment]
#ENC[AES256_GCM,data:vx7fH7AHx61LG8T1niaBkTUEtnKzXDehpVwPnPusjts92oaan+C5lBoLvrnkgW5PVBrZLrnOzzaS19KSN+DRIlYi+a6QBzG/,iv:MeuOtIeeZF5YFO3c53m1NBOMokP4sszQzAccsZ0eNmg=,tag:UptLmq+tytH3hwPrCMy2yQ==,type:comment]
#
#ENC[AES256_GCM,data:xjjVb/cYj0c+itWcV7BEHU3IEtzyO0DLZmi3o+JkNoIEcDLY8CcPQfSZ8RgjmQU83IVH,iv:SroJpqOSMzpmyPj04xgFY8uBM6TyB+D7TU7aeyZn9ZE=,tag:rExHxhrU7lZ5EuaBXLe+PQ==,type:comment]
#ENC[AES256_GCM,data:uJT6Lzpo8peqQ7vna0I8FKkq2B8zDwefB6AvMfYGHR1V+eiTfQ==,iv:YCIJibe9Zzod4f/CndW867CEXrevd6FJrdScoGvDw+M=,tag:APWkIwiLdmv7M2Bhav+XOQ==,type:comment]
#ENC[AES256_GCM,data:kVkJBYU1Le0WX6skJnlCz2b/5nhi/X+JYnNfDZq1IfF+EC5HpEJdTSRfz5mAIFlcvzJShXaMSe8gmG2ri8E=,iv:Ea5AFK+SM/pZmNC4nSdjKydj+90RvCZ70lL/bu3UPA8=,tag:Ke5R/A5bSLMvetTTC0hspQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:RPg=,iv:HvAf0P3TWfXqi1UYE/Nd+mXi55419KlLBEj6OegqYqE=,tag:oB6JhxoOjtxih4cxiJlVrQ==,type:str]
kind: ENC[AES256_GCM,data:FOrTly8h,iv:oCfLUSET2bjV0IZtQzXBPft5Dv8n4ePPHUR9wT0GJxE=,tag:uU19plVOP60MsDGb8QGqXQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GYCa8TQAwK8aQkLiCMDNjFm9jq8=,iv:BLRrzKH/bEalP0KtIISU5rq4dI+Uo5i5JnOCWOpZXxg=,tag:rxKF040taA6iMUPsjPcFvg==,type:str]
    namespace: ENC[AES256_GCM,data:MelkF4RSx6/1gSEA,iv:AQZLuOAStz6Ef9CA97Mx4Vj0iB/de3cBna6Zd0q0IX4=,tag:HUASeCAcV00R9Z2EoAikbw==,type:str]
type: ENC[AES256_GCM,data:5XiujQmE,iv:9Zn6R2DXmOKDzLRHZFVt5qJyP0flUeTr0tfgL3xIJzo=,tag:TA2hhBKNT4kk1oJKyKxFcw==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:9gC1hwDe+Cy5TNyxhp7aS02wACFB2dx5Q+z49QLIBbsau8ZoiSeDWg==,iv:muOjf4f9m0fXFr045yacreDQ1kGi0XHoOHKO6UgR6cE=,tag:4LtsjuDd7GBBh3DfqLR5qQ==,type:str]
sops:
    lastmodified: "2026-07-21T00:52:43Z"
    mac: ENC[AES256_GCM,data:WHtYWuBpnotsiDCd0jIFUfKu/tPwwDLu4quYt57BCwy1QehQ3gl1dFP/8qLpWzEYwz02pgJcTPuo1C5hSpb7sqggo76hXS9/CAZPLJLFr9l6DUgOcIggKkMwqDhsJuuYCZPl/HHu2nFQaG2siRT44hGImJS8k2DaJKCgylwf8sc=,iv:vFkdfRFrDwH4sBltY4/kfAgNk1iCQ6XTlm+8QMlZjBE=,tag:UIhuBMJkRozpII3xTdG9JQ==,type:str]
    pgp:
        - created_at: "2026-07-21T00:51:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1B8bZVuhKLCAQ//XOzRottpFNW5cX9IEcGatadgxmGQUxKYveVJFJlTl9Hj
            ACOQb6VvdlhNFdrafhGVg2ju+CU0BJPVj/IgWudBnrxcGpku3gNlh3ttH/nq3iIS
            MTvV9lRks3Tk/iXgfLIhng7fYzQg/x12MHt9RZAB7bMwVur9HMxgkOpSUGkFZmVE
            dza9CdT8P7QsBQOLJ9wwFRwk2WCim9SDDlkmL42cMe7yBEEzzJwIbn/TwdvnniHR
            c2pelHMPpN64Y5UTgLV7TxoYrejhXuTv/VyKNvfptbStCs3Rtnxwsao23LOkVPgZ
            Ate4z748wvofjgEXnax5btsOiFUOKlnSrPxT0wtW1bI67eyNoOeeeaPoakMBjNGV
            kD4N05R79cwENdYP3lmgdoQSNxio0rzzkik/CiRYePuAwmKcF6t6wF6bLs8dZ+pA
            lfNYaVUdDrMw/dke171xSJUkWm+JAp3LuQGfo6lMumYaUKiflDhjnARLX7V26WuN
            pwBWkAEyPdai1GmIcID1A1TOHQz5ka5YJLTFRuvwnnoqRqQT3OXGhA34CcsvqxNL
            7LqyusWTV46aRI7rEDJn1rX95uO/hgj5m2ac9N9jcAk+GKWvOvfaCmLnP6f+71f6
            bQzjJSme8sR5Es/4rulaHoE/Fcu2VcQl7bGDEjrg13GfRNeoGs03Z8zDZoq4ScrS
            XgHq3x0EuLoj/jwtkbSLQ2QUOIhvNRZ8gj3DI3qKHyLkkZGO3e+ya+4S8W9atgY0
            VvfGa4LUWLBRTlg+P0gADX83jOEXDc/jwRQ5c38mcjT9FCtd6VcODnEUf/0778A=
            =JdGY
            -----END PGP MESSAGE-----
          fp: 50B818296F7698060BF15F77B7819AD0BB898DEE
    unencrypted_suffix: _unencrypted
    version: 3.11.0
