apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: localmovies
  name: localmovies
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/localmovies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localmovies
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: localmovies
    spec:
      containers:
      - image: 192.168.1.8:5000/localmovies-server:latest
        imagePullPolicy: Always
        name: localmovies-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: application-config 
          mountPath: /opt/localmovies/config
          readOnly: true
        - name: series
          mountPath: /opt/localmovies/data
          readOnly: true
      dnsConfig:
        nameservers:
         - 8.8.8.8
      volumes:
      - name: application-config
        configMap:
          name: localmovies
          items:
          - key: bootstrap.properties
            path: bootstrap.properties
      - name: series
        hostPath:
          path: /media/nathan/server-data
          type: Directory
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}

