apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: prom/prometheus 
        imagePullPolicy: IfNotPresent
        name: prometheus
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
          readOnly: false
        - name: prometheus-data
          mountPath: /prometheus
          readOnly: false
      dnsConfig:
        nameservers:
         - 8.8.8.8
      volumes:
       - name: prometheus-config
         configMap:
          name: prometheus
          items:
          - key: prometheus-config.yml
            path: prometheus.yml
       - name: prometheus-data
         hostPath:
           path: /opt/prometheus
           type: Directory
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

