apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: youtrack
  name: youtrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtrack
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: youtrack
    spec:
      hostAliases:
      - ip: 192.168.1.8
        hostnames:
        - "docker-registry"
      containers:
      - image: jetbrains/youtrack:2018.1.41826 
        imagePullPolicy: IfNotPresent
        name: youtrack
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: youtrack-data
          mountPath: /opt/youtrack/data
          readOnly: false
        - name: youtrack-logs
          mountPath: /opt/youtrack/logs
          readOnly: false
        - name: youtrack-conf
          mountPath: /opt/youtrack/conf
          readOnly: false
        - name: youtrack-backups
          mountPath: /opt/youtrack/backups
          readOnly: false
      dnsConfig:
        nameservers:
         - 8.8.8.8
      volumes:
      - name: youtrack-data
        hostPath:
          path: /opt/youtrack/data
          type: Directory
      - name: youtrack-logs
        hostPath:
          path: /opt/youtrack/logs
          type: Directory
      - name: youtrack-conf
        hostPath:
          path: /opt/youtrack/conf
          type: Directory
      - name: youtrack-backups
        hostPath:
          path: /opt/youtrack/backups
          type: Directory
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
