# helm repo add open-webui https://helm.openwebui.com/
# helm -n open-webui upgrade --install open-webui open-webui/open-webui -f open-webui/values.yml

ollama:
  # -- Automatically install Ollama Helm chart from https://otwld.github.io/ollama-helm/. Use [Helm Values](https://github.com/otwld/ollama-helm/#helm-values) to configure
  enabled: true
  ollama:
    gpu:
      enabled: false
    models:
      - llama3.1
      - llama3.2
  persistentVolume:
    enabled: true
  resources:
    requests:
      cpu: "4"
      memory: "6Gi"
    limits:
      cpu: "14"
      memory: "32Gi"

ingress:
  enabled: true
  host: "llm.nathanrahm.com"
  tls: true
  annotations:
    kubernetes.io/tls-acme: 'true'
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"


persistence:
  enabled: true
  size: 8Gi
