# helm repo add open-webui https://helm.openwebui.com/
# helm -n open-webui upgrade --install open-webui open-webui/open-webui -f open-webui/values.yml

ingress:
  enabled: true
  host: "llm.nathanrahm.com"
  tls: true
  annotations:
    kubernetes.io/tls-acme: 'true'
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"

persistence:
  enabled: true
  size: 8Gi

ollama:
  # -- Automatically install Ollama Helm chart from https://otwld.github.io/ollama-helm/. Use [Helm Values](https://github.com/otwld/ollama-helm/#helm-values) to configure
  enabled: true
  ollama:
    gpu:
      enabled: false
    models:
      - llama3.1
      - llama3.2
  persistentVolume:
    enabled: true
  resources:
    requests:
      cpu: "4"
      memory: "6Gi"
    limits:
      cpu: "14"
      memory: "32Gi"
  ingress:
    enabled: true
    hosts:
      - host: ollama.nathanrahm.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ollama-tls
        hosts:
          - ollama.nathanrahm.com
    annotations:
      kubernetes.io/tls-acme: 'true'
      ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/enable-modsecurity: "true"
      nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
      nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.open-webui.svc.cluster.local:4180/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://ollama.nathanrahm.com/oauth2/start?rd=$escaped_request_uri"
#      nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
#      nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
