version: '3'

services:
    vault:
        image: vault:latest
        ports:
          - "8200:8200"
        volumes:
          - /opt/vault/config:/vault/config
        cap_add:
          - IPC_LOCK
        entrypoint: vault server -config /vault/config/config.json
