apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: kong
  name: kong
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kong
    spec:
      hostAliases:
      - ip: "192.168.1.8"
        hostnames:
        - "postgres"
      containers:
      - image: 192.168.1.8:5000/kong
        imagePullPolicy: Always
        name: kong
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsConfig:
        nameservers:
         - 8.8.8.8
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}

