apiVersion: v1
kind: Service
metadata:  
  name: kong
spec:
  type: NodePort
  selector:
    app: kong
  ports:  
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30039
    protocol: TCP
  - name: admin
    port: 8001
    targetPort: 8001
    nodePort: 30030
    protocol: TCP
