apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: localmovie-media-manager
  name: localmovie-media-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localmovie-media-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: localmovie-media-manager
    spec:
      containers:
      - image: {{.Values.localmovies.imageRepository}}/localmovie-media-manager:latest
        imagePullPolicy: Always
        name: localmovie-media-manager
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: application-config 
          mountPath: /opt/localmovie/config
          readOnly: true
        - name: media1
          mountPath: /opt/localmovie/1/LocalMedia
        - name: media2
          mountPath: /opt/localmovie/2/LocalMedia
        - name: secrets
          mountPath: /opt/localmovie/secrets
          readOnly: true
      volumes:
      - name: media1
        nfs:
          server: 192.168.1.189
          path: /LocalMedia1
      - name: media2
        nfs:
          server: 192.168.1.189
          path: /LocalMedia2
      - name: application-config
        configMap:
          name: localmovie-media-manager
          items:
          - key: bootstrap.properties
            path: bootstrap.properties
      - name: secrets
        secret:
# Create this secret via: kubectl create secret generic localmovie-firebase-key --from-file=localmovie-firebase-key.json
          secretName: localmovie-firebase-key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
