# helm upgrade --install -n stable-diffusion stable-diffusion ./stable-diffusion
# Gateway API: Create httproute.yml if deploying (not currently deployed)

image:
  registry: rahmnathan
  tag: 78

persistence:
  capacity:
    data: 100Gi
    output: 100Gi

service:
  timezone: "America/Los_Angeles"