version: '3'

services:
  vpn:
    image: vpn 
    cap_add:
      - net_admin
    devices:
     - "/dev/net/tun"
    volumes:
    - /home/nathan/docker/deluge/vpn/resolv.conf:/etc/resolv.conf
  deluge:
    image: deluge
    network_mode: "service:vpn"
    depends_on:
     - vpn
    volumes:
     - "/home/nathan/Downloads:/root/Downloads"
  nginx:
   image: nginx
   ports:
     - "58846:58846"
     - "8112:8112"
   links:
     - vpn:deluge  
