version: '3'

services:
  airvpn:
    image: airvpn
    cap_add:
      - net_admin
    devices:
      - "/dev/net/tun"
    environment:
      USERNAME: username
      PASSWORD: password
    volumes:
      - "/home/nathan/docker/deluge/vpn/resolv.conf:/etc/resolv.conf"
  deluge:
    image: deluge
    network_mode: "service:airvpn"
    depends_on:
      - airvpn
    volumes:
      - "/home/nathan/Downloads:/root/Downloads"
  nginx:
    image: nginx
    ports:
      - "58846:58846"
      - "8112:8112"
    links:
      - airvpn:deluge