version: '3'

services:
  airvpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    environment:
      TZ: 'America/Chicago'
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - /home/nathan/docker/deluge/vpn:/vpn:z
    dns:
      - 192.168.1.24
    command: -f ''
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
  deluge:
    image: rahmnathan/deluge:latest
    network_mode: "service:airvpn"
    volumes:
      - "/home/nathan/Downloads:/root/Downloads"
  nginx:
    image: rahmnathan/nginx:deluge
    ports:
      - "58846:58846"
      - "8112:8112"
    links:
      - airvpn:deluge