version: '3'

services:
  airvpn:
    image: rahmnathan/airvpn
    cap_add:
      - net_admin
    environment:
      TZ: 'America/Chicago'
    restart: always
    volumes:
      - /dev/net:/dev/net:z
      - /home/nathan/docker/deluge/airvpn/AirVPN_Canada_UDP-443.ovpn:/config.ovpn
    dns: 1.1.1.1
  deluge:
    restart: always
    image: rahmnathan/deluge:latest
    network_mode: "service:airvpn"
    volumes:
      - "/home/nathan/Downloads:/root/Downloads"
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - "58846:58846"
      - "8112:8112"
      - "9898:9898"
      - "9117:9117"
    links:
      - airvpn:deluge
    volumes:
      - "/home/nathan/docker/deluge/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/home/nathan/docker/deluge/nginx/ssl/:/etc/nginx/ssl/"