version: '3'

services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
  openvpn-tcp:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn-tcp
    ports:
      - "443:443/tcp"
    restart: always
    volumes:
      - ./openvpn-data-tcp/conf:/etc/openvpn
  openvpn-http:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn-http
    ports:
      - "80:80/tcp"
    restart: always
    volumes:
      - ./openvpn-data-http/conf:/etc/openvpn
