# helm upgrade --install -n audiobookshelf audiobookshelf ./audiobookshelf
# Gateway API HTTPRoute is included in this chart.

### Apply volume-config/* first if restoring existing PV/PVCs from backup.

image:
  registry: ghcr.io/advplyr
  tag: 2.35.1

persistence:
  capacity:
    audiobooks: 100Gi
    config: 5Gi
    metadata: 25Gi
  existingClaim:
    audiobooks: audiobookshelf-audiobooks
    config: audiobookshelf-config
    metadata: audiobookshelf-metadata

service:
  timezone: "America/Los_Angeles"
