# helm -n nfs-pv-provisioner install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner -f nfs-pv-provisioner/values.yml

nfs:
  server: 192.168.1.189
  path: /export/PersistentVolumes
  mountOptions:
    - nolock
    - soft
    - rw

storageClass:
  defaultClass: true