# helm install -n nfs-pv-provisioner nfs-pv-provisioner stable/nfs-client-provisioner --values nfs-pv-provisioner/values.yml

nfs:
  server: 192.168.1.189
  path: /export/PersistentVolumes
  mountOptions:
    - nolock
    - soft
    - rw

storageClass:
  defaultClass: true