# helm -n nfs-pv-provisioner install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner -f nfs-pv-provisioner/values.yml

nfs:
  server: 10.0.0.195
  path: /export/PersistentVolumes1
  mountOptions:
    - nolock
    - soft
    - rw

storageClass:
  defaultClass: true