# helm install -n vault vault hashicorp/vault --values vault/values.yml
# Gateway API: Create httproute.yml if deploying (not currently deployed)

server:
  ingress:
    enabled: false
  ui:
    enabled: true