version: '2'

# Using with CNAME records for subdomains.

services:
  cloudflare-nathanrahm-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=<api-key>
      - ZONE=nathanrahm.com
      - PROXIED=true
