version: '2'

# DDNS for origin subdomain. Other subdomains CNAME to this.

services:
  cloudflare-nathanrahm-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=<api-key>
      - ZONE=nathanrahm.com
      - SUBDOMAIN=k8x9m2q7
      - PROXIED=false
