# Apply these secrets BEFORE running helm install
# kubectl apply -f mealie/secrets.yaml -n mealie
# Then run: helm upgrade --install -n mealie mealie ./mealie --create-namespace

apiVersion: v1
kind: Secret
metadata:
  name: mealie-db-credentials
  namespace: mealie
  labels:
    app: mealie
type: Opaque
stringData:
  username: mealie
  password: "mealie-secure-pw-2026"
---
apiVersion: v1
kind: Secret
metadata:
  name: mealie-oidc-credentials
  namespace: mealie
  labels:
    app: mealie
type: Opaque
stringData:
  # Generate this in Keycloak when creating the client
  client-secret: "J8N6fciRi5oUDKqDsWrIYrDhWBtU2rF2"
