apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: cluster.local/nfs-subdir-external-provisioner
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-postgres-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: postgres-postgresql-2
    namespace: postgres
  mountOptions:
  - nolock
  - soft
  - rw
  nfs:
    path: /export/PersistentVolumes1/postgres-data-postgresql-0-pvc-ea7ef126-bc56-4b63-9ae3-6ffe14c98f25
    server: 10.0.0.195
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
