initdbScripts:
  vault.sql: |
    create user vault with password 'pw123';
    create database vault owner vault;
    \c vault

    SET SESSION AUTHORIZATION vault;

    CREATE TABLE vault_kv_store (
      parent_path TEXT COLLATE "C" NOT NULL,
      path        TEXT COLLATE "C",
      key         TEXT COLLATE "C",
      value       BYTEA,
      CONSTRAINT pkey PRIMARY KEY (path, key)
    );

    CREATE INDEX parent_path_idx ON vault_kv_store (parent_path);
    RESET SESSION AUTHORIZATION;
  keycloak.sql: |
    create user keycloak with password 'pw123';
    create database keycloak owner keycloak;

postgresqlPassword: pw123
postgresqlUsername: postgres
postgresqlDatabase: postgres

livenessProbe:
  enabled: true
  initialDelaySeconds: 1500

readinessProbe:
  enabled: true
  initialDelaySeconds: 1500