# helm install -n postgres postgresql bitnami/postgresql --values postgres/values.yml

initdbScripts:
  vault.sql: |
    create user vault with password 'pw123';
    create database vault owner vault;
    \c vault

    SET SESSION AUTHORIZATION vault;

    CREATE TABLE vault_kv_store (
      parent_path TEXT COLLATE "C" NOT NULL,
      path        TEXT COLLATE "C",
      key         TEXT COLLATE "C",
      value       BYTEA,
      CONSTRAINT pkey PRIMARY KEY (path, key)
    );

    CREATE INDEX parent_path_idx ON vault_kv_store (parent_path);
    RESET SESSION AUTHORIZATION;
  keycloak.sql: |
    create user keycloak with password 'pw123';
    create database keycloak owner keycloak;

postgresqlPassword: pw123
postgresqlUsername: postgres
postgresqlDatabase: postgres

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

metrics:
  enabled: false

image:
  tag: 15-debian-11

primary:
  resources:
    requests:
      cpu: "1"
      memory: "1G"
    limits:
      cpu: "4"
      memory: "4G"

# To mount and run init scripts?
#  containerSecurityContext:
#    readOnlyRootFilesystem: false

  # Removed this for fresh deployment
  persistence:
    existingClaim: postgres-postgresql-2